### ISSUE TITLE
Documents on usage

### ISSUE THREAD

**Issue by qiuwei** [amitjindal/generator-jhipster-postgresuuid-converter#1]
Could you add a section in the document about how to use it?

I suppose it works on an already generated project?

**Comment by amitjindal** [comment]
Hi @qiuwei 
I just added some notes. See if these help.

**Comment by qiuwei** [comment]
Thanks a lot. It's really helpful.

Meanwhile, you might want to mention this bug in the usage as well.
https://github.com/hipster-labs/generator-jhipster-entity-audit/issues/63

**Comment by amitjindal** [comment]
Not aware of that issue. Will read and add to usage.
